const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const O=require('../official-events-provider');const Store=require('../public-events-store');const Runtime=require('../public-events-runtime');
test('CVM IPE classification never turns a generic document into an event',()=>{assert.equal(O.classifyDocument({title:'Fato Relevante'}),'OTHER_CASH_EVENT_CANDIDATE');assert.equal(O.extractStructuredEvent({title:'Fato Relevante',ticker:'PETR4'}).ok,false);});
test('official structured extraction requires deterministic fields',()=>{const x=O.extractStructuredEvent({category:'Aviso aos Acionistas',ticker:'PETR4',eventType:'JCP',paymentDate:'2026-10-10',baseDate:'2026-09-20',amount:0.42,id:'doc-1',url:'https://cvm.test/doc'});assert.equal(x.ok,true);assert.equal(x.event.eventType,'JCP');assert.equal(x.event.sourceRank,1);});
test('CVM provider discovers the official IPE catalog read-only',async()=>{const p=O.createCvmIpeProvider({fetchImpl:async()=>({ok:true,json:async()=>({result:{resources:[{name:'2026',url:'https://cvm.test/2026.zip'}]}})})});const x=await p.getDocumentIndex();assert.equal(x.ok,true);assert.equal(x.resources.length,1);});
test('official provider connects deterministic documents to the existing pipeline',async()=>{const p=O.createCvmIpeProvider();const x=await p.processDocuments([{url:'https://cvm.gov.br/doc',metadata:{ticker:'ABCD3'}}],{processDocument:async()=>({ok:true,events:[{symbol:'ABCD3',eventType:'DIVIDEND'}],document:{ok:true}})});assert.equal(x.ok,true);assert.equal(x.events.length,1);assert.equal(x.documentsFetched,1);});
test('legacy entrypoint exposes the official pipeline without auto-fetch or realization',()=>{const source=fs.readFileSync(require.resolve('../index.html'),'utf8');assert.match(source,/__OFFICIAL_EVENTS_PIPELINE__/);assert.match(source,/mode:'SHADOW_READ_ONLY'/);assert.match(source,/BROWSER_CORS_UNAVAILABLE/);});
test('public event cache is versioned and isolated from civ5',()=>{const s=Store.createMemoryStorage();const x=Store.write(s,{events:[{symbol:'PETR4'}],quotes:{}});assert.equal(x.version,1);assert.deepEqual(Store.read(s).events,[{symbol:'PETR4'}]);assert.equal(Store.KEY,'carteira_public_corporate_events_v1');});
test('public event upsert is idempotent and keeps source evidence',()=>{const s=Store.createMemoryStorage();const event={symbol:'PETR4',eventType:'DIVIDEND',paymentDate:'2026-09-25',valuePerUnitGross:1,sourceProvider:'official',sourceDocumentId:'doc-1'};const a=Store.upsert(s,[event],{now:'2026-09-01T00:00:00Z'});const b=Store.upsert(s,[event],{now:'2026-09-01T00:00:00Z'});assert.equal(a.added,1);assert.equal(b.duplicates,1);assert.equal(Store.read(s).events.length,1);});
test('runtime is cache-first and reports public refresh without portfolio writes',async()=>{const s=Store.createMemoryStorage();let updates=[];const runtime=Runtime.create({store:Store,storage:s,provider:{syncPortfolio:async()=>({status:'UPDATED',events:[{symbol:'PETR4'}],portfolioWrites:0,cloudWrites:0})},onUpdate:x=>updates.push(x.status)});await runtime.start();assert.deepEqual(runtime.read().events,[{symbol:'PETR4'}]);assert.ok(updates.includes('UPDATING'));runtime.stop();});
