const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const source = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');

test('market refresh blocks duplicate in-flight work', () => {
  const start = source.indexOf('async function fetchQuotes(');
  const end = source.indexOf('async function fetchAutoProventos(', start);
  const snippet = source.slice(start, end);
  assert.match(snippet, /if\(S\.qInFlight\) return/);
  assert.match(snippet, /S\.qInFlight=true/);
  assert.match(snippet, /S\.qInFlight=false/);
});

test('automatic proventos keep debounce, ownership and running guards', () => {
  const start = source.indexOf("function scheduleAutoProventosGratis(");
  const end = source.indexOf('function load(){', start);
  const snippet = source.slice(start, end);
  assert.match(snippet, /setTimeout\(\(\)=>runAutoProventosGratis\(reason\), 1400\)/);
  assert.match(snippet, /if\(S\.autoProvRunning\) return/);
  assert.match(snippet, /if\(!isEditOwner\(\)\) return/);
  assert.match(source, /function isAutoGeneratedProvento\(p\)/);
});

test('local test mode does not initialize external Firebase', () => {
  const start = source.indexOf('function initFirebase(){');
  const end = source.indexOf('// ═', start);
  const snippet = source.slice(start, end);
  assert.match(snippet, /if\(isLocalTestMode\(\)\)/);
  assert.match(snippet, /FB\.access\.reason = 'Modo de teste local'/);
  assert.doesNotMatch(snippet.slice(0, snippet.indexOf("if(isLocalTestMode())") + 1), /firebase\.initializeApp/);
});
