const test=require('node:test'); const assert=require('node:assert/strict'); const T=require('../portfolio-event-timeline.js');
const base={proventos:[{id:'d1',ticker:'PETR4',date:'2026-09-20',type:'Dividendo',value:0},{id:'j1',ticker:'BBAS3',paymentDate:'2026-08-15',type:'JCP',value:10},{id:'ref',ticker:'PETR4',date:'2026-09-01',type:'Dividendo',value:99,sourceEventKind:'reference'}],aportes:[{id:'buy',ticker:'PETR4',date:'2026-07-01',operation:'compra',totalValue:100}],corporateEvents:[{id:'c1',symbol:'PETR4',eventType:'DIVIDEND',paymentDate:'2026-10-01',status:'EXPECTED',expectedNet:12}]};
test('normaliza datas YYYY-MM-DD sem deslocamento de fuso',()=>assert.equal(T.normalizeDate('2026-09-20').display,'20/09/2026'));
test('ordena cronologicamente e preserva zero legítimo',()=>{const e=T.buildTimeline(base);assert.equal(e[0].date,'2026-10-01');assert.equal(e.find(x=>x.id==='d1').value,0);});
test('distingue desconhecido de zero',()=>{const e=T.buildTimeline({proventos:[{id:'u',ticker:'A',date:'2026-01-01',type:'Dividendo'}]});assert.equal(e[0].value,null);assert.equal(e[0].valueState,'unknown');});
test('exclui referência do total de renda',()=>assert.equal(T.incomeTotal(T.buildTimeline(base)),10));
test('mantém corporate shadow/reference fora do realizado',()=>assert.equal(T.buildTimeline(base).find(x=>x.id==='c1').status,'REFERENCE'));
test('deduplica identidade estável',()=>assert.equal(T.normalizeInputs({proventos:[{id:'x',date:'2026-01-01'},{id:'x',date:'2026-01-01'}]}).length,1));
test('agrupa mês e ano com total somente somável',()=>{const e=T.buildTimeline(base);assert.equal(T.groupBy(e,'month').some(x=>x.key==='2026-09'),true);assert.equal(T.groupBy(e,'year')[0].key,'2026');});
test('filtra por tipo, status, ativo e busca',()=>{const e=T.buildTimeline(base);assert.equal(T.applyFilters(e,{type:'PURCHASE'}).length,1);assert.equal(T.applyFilters(e,{status:'REFERENCE'}).length,2);assert.equal(T.applyFilters(e,{search:'bbas'}).length,1);});
test('resumo é determinístico e factual',()=>assert.match(T.summary(T.buildTimeline(base)).text,/evento/));
test('período atual remove passado',()=>assert.equal(T.buildTimeline(base,{period:'month',now:new Date('2026-09-25')}).some(e=>e.date==='2026-10-01'),false));
test('data inválida não vira zero',()=>assert.equal(T.normalizeDate('not-a-date').state,'invalid'));
test('ordenação reversa mantém empate determinístico',()=>{const e=T.buildTimeline({proventos:[{id:'b',ticker:'B',date:'2026-01-01'},{id:'a',ticker:'A',date:'2026-01-01'}]});assert.deepEqual(e.map(x=>x.id),['a','b']);});
test('agrupamento mensal preserva eventos sem data',()=>assert.equal(T.groupBy(T.buildTimeline({proventos:[{id:'u',ticker:'A'}]}))[0].key,'unknown'));
test('agrupamento anual usa ano factual',()=>assert.equal(T.groupBy(T.buildTimeline({proventos:[{id:'a',date:'2025-12-01'}]}),'year')[0].key,'2025'));
test('YTD é limitado ao ano corrente',()=>assert.equal(T.buildTimeline({proventos:[{id:'old',date:'2025-12-31'},{id:'now',date:'2026-02-01'}]},{period:'year',now:new Date('2026-09-19')}).length,1));
test('12 meses aceita janela móvel',()=>assert.equal(T.buildTimeline({proventos:[{id:'old',date:'2025-09-01'},{id:'new',date:'2026-09-01'}]},{period:'12m',now:new Date('2026-09-19')}).length,1));
test('DIVIDEND é classificado como renda realizada',()=>assert.equal(T.buildTimeline({proventos:[{id:'d',date:'2026-01-01',type:'Dividendo',value:1}]})[0].type,'DIVIDEND'));
test('JCP é classificado sem perder valor',()=>{const e=T.buildTimeline({proventos:[{id:'j',date:'2026-01-01',type:'JCP',value:2}]})[0];assert.equal(e.type,'JCP');assert.equal(e.value,2);});
test('rendimento é somável somente realizado',()=>assert.equal(T.incomeTotal(T.buildTimeline({proventos:[{id:'r',date:'2026-01-01',type:'Rendimento',value:3}]})),3));
test('compra é movimentação, não renda',()=>assert.equal(T.incomeTotal(T.buildTimeline({aportes:[{id:'b',date:'2026-01-01',operation:'compra',totalValue:10}]})),0));
test('venda permanece venda sem inferir lucro',()=>assert.equal(T.buildTimeline({aportes:[{id:'s',date:'2026-01-01',operation:'venda',value:10}]} )[0].type,'SALE'));
test('aporte é separado de compra',()=>assert.equal(T.buildTimeline({aportes:[{id:'a',date:'2026-01-01',operation:'aporte',value:10}]} )[0].type,'CONTRIBUTION'));
test('evento corporate não altera posição',()=>{const e=T.buildTimeline({corporateEvents:[{id:'c',symbol:'A',eventType:'SPLIT',paymentDate:'2026-01-01'}]})[0];assert.equal(e.status,'REFERENCE');assert.equal(e.value,null);});
test('fonte e provenance reais são preservadas',()=>{const e=T.buildTimeline({proventos:[{id:'a',date:'2026-01-01',source:'ledger',observedAt:'2026-01-02'}]})[0];assert.equal(e.source,'ledger');assert.equal(e.provenance.observedAt,'2026-01-02');});
test('não inventa provenance',()=>{const e=T.buildTimeline({proventos:[{id:'a',date:'2026-01-01'}]})[0];assert.equal(e.provenance.observedAt,'');});
test('busca por ticker',()=>assert.equal(T.applyFilters(T.buildTimeline(base),{search:'PETR4'}).length,4));
test('busca por nome',()=>assert.equal(T.applyFilters(T.buildTimeline({proventos:[{id:'a',date:'2026-01-01',name:'Fundo Azul'}]}),{search:'azul'}).length,1));
test('filtro por origem',()=>assert.equal(T.applyFilters(T.buildTimeline(base),{source:'DIVIDENDS'}).length,3));
test('filtro por realized',()=>assert.equal(T.applyFilters(T.buildTimeline(base),{status:'REALIZED'}).length,3));
test('filtro por asset',()=>assert.equal(T.applyFilters(T.buildTimeline(base),{asset:'BBAS3'}).length,1));
test('resumo conta ativos distintos',()=>assert.equal(T.summary(T.buildTimeline(base)).assets,2));
test('total de renda não inclui valor desconhecido',()=>assert.equal(T.incomeTotal(T.buildTimeline({proventos:[{id:'u',date:'2026-01-01',type:'JCP'}]})),0));
test('total de renda soma zero legítimo sem perder o zero',()=>{const e=T.buildTimeline({proventos:[{id:'z',date:'2026-01-01',type:'JCP',value:0}]});assert.equal(T.incomeTotal(e),0);assert.equal(e[0].valueState,'known');});
test('payment date é exposta separadamente',()=>assert.equal(T.buildTimeline({proventos:[{id:'a',date:'2026-01-01',paymentDate:'2026-01-05'}]})[0].paymentDate,'2026-01-05'));
test('ex date é exposta sem substituir a data do evento',()=>{const e=T.buildTimeline({corporateEvents:[{id:'a',exDate:'2026-01-02',paymentDate:'2026-01-05'}]})[0];assert.equal(e.exDate,'2026-01-02');assert.equal(e.date,'2026-01-05');});
test('data ISO com horário permanece estável',()=>assert.equal(T.normalizeDate('2026-01-01T12:00:00-03:00').key,'2026-01-01'));
test('tipo desconhecido não é convertido em provento',()=>assert.notEqual(T.buildTimeline({proventos:[{id:'x',date:'2026-01-01',type:'Evento especial',value:5}]})[0].type,'DIVIDEND'));
test('fonte indisponível continua identificável',()=>assert.equal(T.buildTimeline({corporateEvents:[{id:'x',paymentDate:'2026-01-01',sourceProvider:''}]})[0].source,'CORPORATE_EVENTS'));
test('sem eventos retorna resumo sem falso zero financeiro',()=>{const s=T.summary([]);assert.equal(s.count,0);assert.equal(s.incomeTotal,0);assert.match(s.text,/Nenhum evento|0 evento/);});
test('normalização não muta a fonte',()=>{const input={proventos:[{id:'x',date:'2026-01-01'}]};const before=JSON.stringify(input);T.buildTimeline(input);assert.equal(JSON.stringify(input),before);});
test('IDs de fontes diferentes não colidem por ticker/data',()=>assert.equal(T.normalizeInputs({proventos:[{id:'a',ticker:'X',date:'2026-01-01'}],aportes:[{id:'b',ticker:'X',date:'2026-01-01'}]}).length,2));
test('reference corporativo não entra no resumo realizado',()=>{const s=T.summary(T.buildTimeline({corporateEvents:[{id:'x',paymentDate:'2026-01-01',status:'EXPECTED'}]}));assert.equal(s.realized,0);assert.equal(s.reference,1);});
test('filtro desconhecido não elimina evento sem data',()=>assert.equal(T.filterPeriod(T.buildTimeline({proventos:[{id:'x'}]}),{period:'month',now:new Date('2026-01-01')}).length,1));
